export SDKVERSION=13.7

ARCHS = arm64 arm64e


include $(THEOS)/makefiles/common.mk

TWEAK_NAME = JodelConfirmVotes

JodelConfirmVotes_FILES = Tweak.x
JodelConfirmVotes_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
